services:
  - name: dev-db
    image: "postgres"
    env:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=fiu-fit-users"
    env_secret:
      - "DATABASE_URL"
    ports:
      - 5434:5432
    health_check:
      cmd: ["pg_isready", "-U", "postgres"]
    automatic_tls:
      renew_interval_days: 30
    network:
      - name: fiu-fit

  - name: test-db
    image: "postgres"
    env:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=fiu-fit-users-test"
    env_secret:
      - "TEST_DATABASE_URL"
    ports:
      - 5435:5432
    health_check:
      cmd: ["pg_isready", "-U", "postgres"]
    automatic_tls:
      renew_interval_days: 30
    network:
      - name: fiu-fit

networks:
  - name: fiu-fit
