services:
  - type: web
    name: dev-db
    env: docker
    plan: free
    image: "postgres"
    dockerCommand: "docker compose up dev-db -d"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: web
          name: Fiu-Fit-users-service

  - type: web
    name: test-db
    plan: free
    env: docker
    image: "postgres"
    dockerCommand: "docker compose up test-db -d"
    envVars:
      -key: DATABASE_URL
      fromService:
        type: web
        name: Fiu-Fit-users-service

