name: TestsWorkFlow

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up package manager
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'yarn'
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Run tests
      run: npm test